sudo: required
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
env:
  - ROS_DISTRO=hydro
install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y ros-hydro-desktop ros-hydro-roscpp-tutorials ros-hydro-rostest python-catkin-tools
before_script:
  - ls
  - mv 20150930/check1.test 20150930/src/beginner_tutorials
  - mv 20150930/check2.test 20150930/src/beginner_tutorials
script:
  - source /opt/ros/hydro/setup.bash
  - cd 20150930
  - catkin build -v -i
  - source devel/setup.bash
  - rospack list
  - rostest beginner_tutorials check1.test
  - rostest beginner_tutorials check2.test
after_failure:
  - find src/ -type d -name .git -prune -o -type f -exec ls -l {} \;
  - rostest -t beginner_tutorials check1.test
  - rostest -t beginner_tutorials check2.test
